### ISSUE TITLE
Release to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-grizzly#2025]
- [x] Uptake new Eclipse versions of dependencies. Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [x] Release to OSSRH staging repository

- [x] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number. 

[How to release first versions of EE4J components](https://wiki.eclipse.org/How_to_release_first_versions_of_EE4J_components)

**Comment by anajosep** [comment]
Uploaded the Eclipse Grizzly artifacts to the OSSRH staging repository.
 https://oss.sonatype.org/service/local/staging/deploy/maven2/org/glassfish/grizzly/

**Comment by arjantijms** [comment]
@anajosep 

That's the "unreachable repo" it seems.

I think you need to run the job with the 1.0.5 parent and use the nexus plugin.

**Comment by arjantijms** [comment]
@anajosep if you click on the link, you get

"Access Denied

Please login before attempting further requests."

Plus, other jobs can't find Grizzly now. Grizzly should appear somewhere here: https://oss.sonatype.org/content/repositories/staging

**Comment by arjantijms** [comment]
cc @m0mus

**Comment by anajosep** [comment]
@arjantijms  I have corrected it and now the bundles are available here https://oss.sonatype.org/content/repositories/staging/org/glassfish/grizzly/. Thanks for pointing it out.

**Comment by arjantijms** [comment]
@anajosep w00t! Thx :)

**Comment by arjantijms** [comment]
@anajosep I did an extra check, and I think artefact "grizzly-bom" is still missing here:

https://oss.sonatype.org/content/repositories/staging/org/glassfish/grizzly/

The other ones look fine, but that one should be there as well if I'm not mistaken.

**Comment by senivam** [comment]
@anajosep grizzly-bom is missing from staging. Could you please publish it as well?

**Comment by arjantijms** [comment]
cc @m0mus because the grizzly-bom is missing, OpenMQ among others can not actually use this dependency now

**Comment by anajosep** [comment]
https://ci.eclipse.org/grizzly/job/Grizzly-master_release/43/consoleFull 
These are the build logs. I do not see any error related to grizzly-bom 
I am using release:clean release:prepare and release:perform to make the release.

I see this below log where it says, it is staged to local staging area in OSSRH.
```
    [INFO] Installing /jobs/genie.grizzly/Grizzly-master_release/workspace/target/checkout/bom/pom.xml to /opt/public/hipp/homes/genie.grizzly/.m2/repository/org/glassfish/grizzly/grizzly-bom/2.4.4/grizzly-bom-2.4.4.pom
    [INFO] 
    [INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ grizzly-bom ---
    Uploading to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/glassfish/grizzly/grizzly-bom/2.4.4/grizzly-bom-2.4.4.pom
```
But don't see this artifact here in the snapshot URL. 
Should I add some configuration to include this or could this be a bug in nexus-staging-maven-plugin ?

**Comment by senivam** [comment]
@anajosep there are no errors, however grizzly-bom is still not in staging:

https://oss.sonatype.org/content/groups/staging/org/glassfish/grizzly/

it shall be listed there but it's missing (probably staging is not closed, so grizzly-bom is not visible at https://oss.sonatype.org/content/groups/staging/org/glassfish/grizzly/)

**Comment by senivam** [comment]
@anajosep , @arjantijms fixed, I've closed the staging , now it's listed there:

https://oss.sonatype.org/content/groups/staging/org/glassfish/grizzly/
